activeProfile: gurobiRun

profiles:
    clusterInvestigation:
        mode: CLUSTERINVESTIGATION
        bothRevenueDistribution: false
        parameterTuning:
            parameter: CONSIDEROUTLIERS
            startValue: 0.6
            endValue: 1.4
            stepSize: 0.2
        runs: 1
        testSet: base
        budgetFactor: 1.0
        clusterElimination: base
        clusterEliminationThreshold: 20.0
        solver: gurobi
        gurobi:
            clusterStartNode: mean
        clustering: KMEANSSPLIT
        budgetDistribution: ELZEINWITHMIN
        budgetWeight: 0.2
        revenueDistribution: random
        clusterSize: 24

    gurobiRun:
        mode: PARAMETERSEARCH
        bothRevenueDistribution: false
        parameterTuning:
            parameter: clusterEliminationThreshold
            startValue: 0.50
            endValue: 1.0
            stepSize: 0.1
        runs: 1
        testSet: base
        budgetFactor: 1.0
        clusterElimination: LAST
        clusterEliminationThreshold: 20.0
        solver: gurobi
        gurobi:
            clusterStartNode: mean
        clustering: KMEANSSPLIT
        budgetDistribution: ELZEINWITHMIN # considerClusterMean, considerClusterMedian, considerClusterMeanAndMedian, considerClusterMeanAndMedianWithOutliers, considerClusterMeanAndMedianWithOutliersAndOutliers, considerClusterMeanAndMedianWithOutliersAndOutliersAndClusterSize
        budgetWeight: 0.2
        revenueDistribution: random
        clusterSize: 24