activeProfile: gurobiRun

profiles:
    clusterInvestigation:
        mode: clusterInvestigation
        analysis:
            resultPath: "results/clusterflat"
        bothRevenueDistribution: false
        runs: 1
        parameterTuning:
            parameter: clusterOpBudget
            startValue: 0.30
            endValue: 0.90
            stepSize: 0.1
        instance:
            testSet: base
            budgetFactor: 1.0
            revenueDistribution: random
        algorithm:
            solver: gurobi
            clusterConnector: op
            clusterElimination: none
            clustering: KMEANSSPLIT
            clusteringStatistic: MEAN
            budgetDistribution: ELZEINWITHMIN # considerClusterMean, considerClusterMedian, considerClusterMeanAndMedian, considerClusterMeanAndMedianWithOutliers, considerClusterMeanAndMedianWithOutliersAndOutliers, considerClusterMeanAndMedianWithOutliersAndOutliersAndClusterSize
            gurobi:
                clusterStartNode: mean
        parameter:
            clusterEliminationThreshold: 0.6
            budgetWeight: 0.2
            clusterSize: 25

    gurobiRun:
        mode: RUN  # Possible values: RUN, PARAMETERSEARCH, COMPARERESULTS
        analysis:
            resultPath: "results/clusterallflat"
        bothRevenueDistribution: false
        runs: 1
        parameterTuning:
            parameter: clusterOpBudget
            startValue: 0.30
            endValue: 0.90
            stepSize: 0.1
        instance:
            testSet: one  # Possible values: ONE, HARD, BASE, ALL, TRAIN
            budgetFactor: 1.00
            revenueDistribution: random  # Possible values: RANDOM, FLAT
        algorithm:
            solver: gurobi  # Possible values: gurobi, ea4op
            clusterConnector: op  # Possible values: TSP, OP
            clusterElimination: none  # Possible values: BASE, SPARSITY, LAST, NONE
            clustering: KMEANSUPPERBOUNDIGNOREOUTLIERS  # Possible values: KMEANS, KMEANSUPPERBOUNDIGNOREOUTLIERS, KMEANSSPLIT, KMEANSFLOW deprecated: KMEANSCAPACITATED, KMEANSCAPACITATEDCUSTOM, KMEANSANDCORRECTLATER, KMEANSUPPERBOUND
            clusteringStatistic: mean # Possible values: MEAN, MEDIAN
            budgetDistribution: ELZEINWITHMIN # Possible values: ELZEIN, ELZEINWITHMIN, CONSIDEROUTLIERS, CONSIDERCLUSTERMEAN, NAIVE
            gurobi:
                clusterStartNode: mean  # Possible values: MEAN, MEDIAN, NONE
        parameter:
            clusterEliminationThreshold: 0.5
            budgetWeight: 0.2
            clusterSize: 25
