activeProfile: gurobiRun

profiles:
    clusterInvestigation:
        mode: clusterInvestigation
        bothRevenueDistribution: false
        runs: 1
        parameterTuning:
            parameter: clusterOpBudget
            startValue: 0.30
            endValue: 0.90
            stepSize: 0.1
        instance:
            testSet: base
            budgetFactor: 1.0
            revenueDistribution: random
        algorithm:
            solver: gurobi
            clusterConnector: op
            clusterElimination: none
            clustering: KMEANSSPLIT
            budgetDistribution: ELZEINWITHMIN # considerClusterMean, considerClusterMedian, considerClusterMeanAndMedian, considerClusterMeanAndMedianWithOutliers, considerClusterMeanAndMedianWithOutliersAndOutliers, considerClusterMeanAndMedianWithOutliersAndOutliersAndClusterSize
            gurobi:
                clusterStartNode: mean
        parameter:
            clusterOpBudget: 0.4
            clusterEliminationThreshold: 0.6
            budgetWeight: 0.2
            clusterSize: 25

    gurobiRun:
        mode: RUN  # Possible values: RUN, PARAMETERSEARCH, CLUSTERINVESTIGATION
        bothRevenueDistribution: false
        runs: 10
        parameterTuning:
            parameter: clusterOpBudget
            startValue: 0.30
            endValue: 0.90
            stepSize: 0.1
        instance:
            testSet: base  # Possible values: ONE, HARD, BASE, ALL, TRAIN
            budgetFactor: 0.5
            revenueDistribution: random  # Possible values: RANDOM, FLAT
        algorithm:
            solver: gurobi  # Possible values: gurobi, ea4op
            clusterConnector: op  # Possible values: TSP, OP
            clusterElimination: none  # Possible values: BASE, SPARSITY, LAST, NONE
            clustering: KMEANSUPPERBOUNDIGNOREOUTLIERS  # Possible values: KMEANS, KMEANSANDCORRECTLATER, KMEANSUPPERBOUND, KMEANSUPPERBOUNDIGNOREOUTLIERS, KMEANSCAPACITATED, KMEANSCAPACITATEDCUSTOM, KMEANSSPLIT
            budgetDistribution: ELZEINWITHMIN  # Possible values: ELZEIN, ELZEINWITHMIN, CONSIDEROUTLIERS, CONSIDERCLUSTERMEAN, NAIVE
            gurobi:
                clusterStartNode: mean  # Possible values: MEAN, MEDIAN, NONE
        parameter:
            clusterOpBudget: 0.5
            clusterEliminationThreshold: 0.4
            budgetWeight: 0.2
            clusterSize: 25
